import { IdName } from './id-name';
import { SystemType } from '../features/systems/system-type';
import { SystemLocation } from './system-location';
import { SystemWash } from './system-wash';
import { SystemCriteria } from './system-criteria';

export interface System {
  id: string;
  type: SystemType;
  name: string;
  KWP: number;
  AC: number;
  apiId: Array<string | number | null>;
  portalUrl: string | null;
  startTime: Date;
  annualPredictionPerMonth: number[];
  excludeFromAverage?: number;
  taoz: 'low' | 'high' | null;
  regulation?: number;
  location: SystemLocation | null;
  client?: {
    name: string;
    id: string;
  };
  lastConnectionTime?: string;
  comments: string;
  contactsIds: string[];
  contract: string;
  converters: { model: string; amount: number }[];
  power?: number;
  panelType?: string;
  numOfPanels?: number;
  communication?: string;
  installer?: string;
  monitorPriceKw?: number;
  azimuth?: number;
  tilt?: number;
  isTracker?: boolean;
  washControl?: boolean;
  autoWash?: boolean;
  washType?: string;
  washRate?: number;
  additionalContract?: string;
  contractStartTime?: any;
  annualCheckDate?: any;
  isActive?: boolean;
  isPvsyst: boolean;
  source?: 'project' | 'new';
  criteria?: SystemCriteria;
}
